# Usage: conda env create -f environment.yml
name: olla
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.3.*
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - arviz
  - pip
  - pip:
      - -e .
